CREATE DATABASE ala 


CREATE TABLE `hdzs` (
  `zsid` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `zspicture` VARCHAR(500) DEFAULT NULL COMMENT '图片（存放图片地址）',
  `zsname` VARCHAR(50) DEFAULT NULL COMMENT '活动展示的名称',
  PRIMARY KEY (`zsid`)
) ENGINE=INNODB DEFAULT CHARSET=utf8




CREATE TABLE `order` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `oname` VARCHAR(50) DEFAULT NULL COMMENT '订单名',
  `omessage` VARCHAR(50) DEFAULT NULL COMMENT '订购信息',
  `onum` INT(50) DEFAULT NULL COMMENT '数量',
  `omoney` INT(50) DEFAULT NULL COMMENT '实付款',
  `ostate` VARCHAR(50) DEFAULT NULL COMMENT '交易状态',
  `otime` DATE DEFAULT NULL COMMENT '订单提交时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8


CREATE TABLE `pchd` (
  `hdid` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `hdaddress` VARCHAR(50) DEFAULT NULL COMMENT '活动区域地址',
  `hdtype` VARCHAR(50) DEFAULT NULL COMMENT '活动类型',
  `hdtime` VARCHAR(50) DEFAULT NULL COMMENT '活动启止时间',
  `hdname` VARCHAR(50) DEFAULT NULL COMMENT '活动名称',
  `hdprice` INT(50) DEFAULT NULL COMMENT '活动单价',
  `hddetails` VARCHAR(500) DEFAULT NULL COMMENT '产品详情',
  `hdpicture` VARCHAR(500) DEFAULT NULL COMMENT '图片存放地址',
  `hdstate` VARCHAR(50) DEFAULT NULL COMMENT '活动状态(0.进行中1.截止)',
  PRIMARY KEY (`hdid`)
) ENGINE=INNODB DEFAULT CHARSET=utf8



CREATE TABLE `pcly` (
  `lyid` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `lytype` VARCHAR(50) DEFAULT NULL COMMENT '出游时长(一日游，二日游.....)',
  `lyname` VARCHAR(50) DEFAULT NULL COMMENT '出游项目名称',
  `lyaddress` VARCHAR(50) DEFAULT NULL COMMENT '出游目的地',
  `lypriceA` INT(50) DEFAULT NULL COMMENT '成人单价',
  `lypriceB` INT(50) DEFAULT NULL COMMENT '儿童单价',
  `lyage` INT(50) DEFAULT NULL COMMENT '最低年龄限制（3岁起）',
  `lypicture` VARCHAR(500) DEFAULT NULL COMMENT '图片（存放图片地址）',
  PRIMARY KEY (`lyid`)
) ENGINE=INNODB DEFAULT CHARSET=utf8




CREATE TABLE `user` (
  `userID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `username` VARCHAR(50) DEFAULT NULL COMMENT '用戶名',
  `password` VARCHAR(50) DEFAULT NULL COMMENT '密码',
  `email` VARCHAR(50) DEFAULT NULL COMMENT '邮箱',
  `phone` INT(50) DEFAULT NULL COMMENT '手机号',
  `address` VARCHAR(500) DEFAULT NULL COMMENT '地址',
  `qq` VARCHAR(50) DEFAULT NULL COMMENT 'QQ号',
  `babyname` VARCHAR(50) DEFAULT NULL COMMENT '宝宝名字',
  PRIMARY KEY (`userID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8

